[package]
name = "tonic-grpc-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
criterion = "0.5"

[build-dependencies]
tonic-build = "0.10"

[[bench]]
name = "grpc_benchmark"
harness = false
